### ISSUE TITLE
Volume Scatter error

### ISSUE THREAD

**Issue by diegxhernandxz** [open-stage/blender-dmx#41] opened 2023-04-22 21:21 UTC
hey there, every time i try to use the volume box option this error pops up, ive tried everything i know and nothing works (i have very basic blender knowledge) how do i fix it?
![image](https://user-images.githubusercontent.com/131558078/233807085-f26ae8a6-dfa2-402a-aebb-315f595a0db1.png)

**Comment by girumtibebu** [comment] 2023-07-25 08:55
Same here any option to create volume effects for moving head beams?

**Comment by vanous** [comment] 2023-08-27 12:44
Volumetric beam is supported via scatter but yes, it would be better to have custom shader (if that is the way) with gobo projection capabilities... As for the original poster, did you figure out what the issue is? For discussion, it is better to ask in [discord](https://discord.com/invite/FQVVyc45T9)...

**Comment by vanous** [comment] 2023-09-17 17:47
> hey there, every time i try to use the volume box option this error pops up, ive tried everything i know and nothing works (i have very basic blender knowledge) how do i fix it? ![image](https://user-images.githubusercontent.com/131558078/233807085-f26ae8a6-dfa2-402a-aebb-315f595a0db1.png)

This issue is fixed in latest main and also in latest release.

**Closed by vanous** 2023-09-17 17:47 UTC
